Location/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('location_manager.urls')),
]

location_manager/urls.py
from django.urls import path
from . import views

app_name='lcm'

urlpatterns = [
    path('', views.index, name='index'),
    path('clients', views.ClientView.as_view(), name = 'owners'),
    path('maisons', views.BuildingView.as_view(), name = 'buildings'),
    path('maisons/<int:pk>', views.BuildingDetailView.as_view(), name="building_detail"),
    path('locataires/', views.CustomerDetailView.as_view(), name='customers'),
    path('locataires/<int:pk>', views.CustomerDetailView.as_view(), name='customer_detail'),
    path('print/<int:pk>', views.render_pdf, name="print"),
    path('printpdf/<int:pk>', views.renders_to_pdf, name="printpdf"),
]

location_manager/models.py
from django.db import models
from django.utils import timezone
import time
import datetime

class Client(models.Model):
    firstname = models.CharField(max_length=80)
    lastname = models.CharField(max_length=80)
    
    def __str__(self):
        return ' '.join([self.firstname,self.lastname])

    def get_buildings(self):
        return Maison.objects.filter(owner=self)

    class Meta:
        db_table ='client'

class Maison(models.Model):
    name = models.CharField(max_length=80, blank=True)
    address = models.CharField(max_length=200)
    owner = models.ForeignKey(Client, on_delete=models.CASCADE, related_name="buildings")

    def __str__(self):
        return self.name

    def get_customers(self):
        return Locataire.objects.filter(home=self)

    class Meta:
        db_table ='maison'

class Locataire(models.Model):
    firstname = models.CharField(max_length=80, verbose_name='Prénoms')
    lastname = models.CharField(max_length=80, verbose_name='NOM')
    home = models.ForeignKey(Maison, on_delete=models.CASCADE, related_name="customers",verbose_name='Maison')
    roomid = models. PositiveIntegerField(default=0, verbose_name='N° de Chambre', unique=True)
    startdate = models.DateField(verbose_name="Date D'entrée", default=timezone.localdate)

    def get_payments(self):
        return Paiement.objects.filter(payer=self)

    def __str__(self):
        return ' '.join([self.firstname,self.lastname])

    class Meta:
        db_table ='locataire'

class Paiement(models.Model):
    date = models.DateField(auto_now_add=True)
    payer = models.ForeignKey(Locataire, on_delete=models.CASCADE, related_name='payment', verbose_name='Paiement',)
    paid = models.BooleanField(default=False, verbose_name='Payé')

    def __str__(self):
        return '%s Le %s' %(self.payer, self.date.strftime('%d/%m/%Y'))
    
    class Meta:
        db_table ='paiement'

location_manager/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from django.views import generic
from .models import Maison, Locataire, Client
import pdfkit

def index(request):
    return render(request, template_name='lcm/index.html', context={"subtitle":"Home"})

class ClientView(generic.ListView):
    model = Client
    context_object_name = 'owners'
    template_name = 'lcm/clients.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subtitle'] = 'Liste des Clients' 
        return context

class BuildingView(generic.ListView):
    model = Maison
    context_object_name = 'buildings'
    template_name = 'lcm/buildings.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subtitle'] = 'Maisons à Charge' 
        return context


class BuildingDetailView(generic.DetailView):
    model = Maison
    context_object_name = 'building'
    template_name = 'lcm/building_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['subtitle'] = 'Maison'
        return context

class CustomerDetailView(generic.DetailView):
    model = Locataire
    context_object_name = 'customer'
    template_name = 'lcm/customer_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['subtitle'] = 'Locataire'
        return context

def render_pdf(request, pk):
    customer = get_object_or_404(Locataire, pk=pk)
    name = 'Point de paiement: %s %s' % (customer.lastname, customer.firstname)

    url = '%s/printpdf/%d' % (request.get_host(), pk)

    config = pdfkit.configuration(wkhtmltopdf=r'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdk.exe')
    pdf = pdfkit.from_url(url,'', configuration=config)

    response = HttpResponse(pdf, content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="%s.pdf"' % name
    return response

def renders_to_pdf(request, pk):
    customer = get_object_or_404(Locataire, pk=pk)
    return render(request, template_name='lcm/print.html', context={'customer':customer})

location_manager/templates/lcm/building_detail.html
{% extends 'base.html' %}

{% block content %}
	<h1 class="title">Maison {{ building.name }}</h1>
	<div class="container">
		<div class="col-md-8 mt-3">
			<p class="introduction">
				<ul class="list">
					<li class="list-item">
						<h2>Adresse</h2>: {{building.address}}
					</li>

					<li class="list-item">
						<h2>Nombre de chambres</h2>: {{ building.get_customers.count}}
					</li>

					<!-- Le loyer est il individuel a chaque chambre ou commun à toutes les chambres de la maison ? -->

					<li class="list-item">
						<h2>Habitants</h2>:

						<ul class="list">
							{% for customer in building.get_customers %}
							<li> <a href="{% url 'lcm:customer_detail' customer.pk %}">{{customer.lastname}} {{customer.firstname}}</a> </li>
							{%endfor%}
						</ul>


					</li>


				</ul>

			</p>
		</div>
	</div>
	
{% endblock content %}

location_manager/templates/lcm/buildings.html
{% extends 'base.html' %}

{% block title %}
	<div class="animate__animated animate__bounceIn title"  class="title"><h1>Maisons A Charge</h1></div>
{% endblock %}

{% block content %}

	<table>

		<thead>
			<tr>
				<th scope="col">Nom</th>
				<th scope="col">Adresse</th>
				<th scope="col">Habitants</th>
			</tr>	
		</thead>

		<tbody>
			{% for building in buildings %}
					<tr class="">
						<td {% if building.customers.count > 1 %} rowspan="{{ building.customers.count }}" {% endif %}><a href="{% url 'lcm:building_detail' building.pk %}">{{ building.name }}</a></td>
						<td {% if building.customers.count > 1 %} rowspan="{{ building.customers.count }}" {% endif %}> {{ building.address }}</td>

						{% if building.customers.count >= 1 %} 
						
							{% with building.get_customers|first as first %}
							<td> <a href="{% url 'lcm:customer_detail' first.pk %}">{{ building.get_customers|first }}</a> </td>
							{% endwith %}

						{% else %}
							<td> Vide </td>

						{% endif %}
					</tr>

					{% if building.customers.count >= 1 %} 
					
						{% for customer in building.get_customers|slice:"1:" %}
						<tr>
							<td><a href="{% url 'lcm:customer_detail' customer.pk %}">{{ customer.firstname }} {{ customer.lastname }}</a></td>
						</tr>
						{% endfor %}						

					{% endif %}

			{% endfor %}
		</tbody>

	</table>

{% endblock content %}

location_manager/templates/lcm/clients.html
{% extends 'base.html' %}

{% block title %}
	<div class="animate__animated animate__bounceIn title"  class="title"><h1>Liste des Clients</h1></div>
{% endblock %}


{% block content %}
	<table>

		<thead>
			<tr>
				<th scope="col">Nom</th>
				<th scope="col">Prénoms</th>
				<th scope="col">Maisons</th>
			</tr>
		</thead>

		<tbody>
			{% for owner in owners %}
					<tr class="">
						<td rowspan="{{owner.buildings.count}}">{{ owner.lastname }}</td>
						<td rowspan="{{owner.buildings.count}}">{{ owner.firstname }}</td>

						{% with owner.get_buildings|first as first %}
						<td> <a href="{% url 'lcm:building_detail' first.pk %}">{{ owner.get_buildings|first }}</a> </td>
						{% endwith %}



					</tr>
				{% for building in owner.get_buildings|slice:"1:" %}
					<tr>
						<td> <a href="{% url 'lcm:building_detail' building.pk %}">{{ building.name }}</a> </td>
					</tr>
				{% endfor %}						
			{% endfor %}
		</tbody>

	</table>

{% endblock content %}

location_manager/templates/lcm/customer_detail.html
{% extends 'base.html' %}

{% block title %}
	<div class="animate__animated animate__bounceIn title"  class="title"><h1>Informations Locataire</h1></div>
{% endblock %}

{% block content %}
	<div class="container">
		<div class="col-md-8 mt-3">
			<ul class="list">
				<li class="list-item">
					<h2>Nom</h2>: {{ customer.lastname }}
				</li>

				<li class="list-item">
					<h2>Prénom</h2>: {{ customer.firstname }}
				</li>

				<li class="list-item">
					<h2>Maison</h2>: {{ customer.home }}
				</li>

				<li class="list-item">
					<h2>Chambre n°</h2>: {{ customer.roomid }}
				</li>

				<li class="list-item">
					<h2>Paiements</h2>:

					<table>

						<tr class="tab-head">
							<th scope="col">Date</th>
							<th scope="col">Payé</th>
						</tr>

						{% for p in customer.get_payments %}
						<tr>
							<td> {{p.date }}</td>
							<td> {% if p.paid %} Oui {%else%} Non {%endif%}</td>
						</tr>
						{% endfor %}

					</table>

				</li>
			</ul>
		</div>

	</div>
	<h4 class="list-item"><a href="{% url 'lcm:print' customer.pk %}" target="_blank" rel="noopener noreferrer">Imprimer</a></h4>
	
{% endblock content %}

location_manager/templates/lcm/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="col-md-8 mt-3 left">
        <p class="introduction">
            Locatia vous aide dans tout ce qui est
            gestion de maisons à louer et de locataires.
            Vous devez enregistrer dans cet ordre le
            propriétaire qui est votre client, la maison 
            à louer et les locataires. Un propriétaire a 
            droit d'avoir plusieur maisons. Et une maison
            peut avoir plusieurs locataires. Ce sont là 
            les principales données qu'il vous faut 
            connaître pour évoluer. Sur ce, découvrez nos
            divers propriétaires <a href="{% url 'lcm:owners' %}">ici</a> et les
            maisons enregistrées <a href="{% url 'lcm:buildings' %}">ici</a>
        </p>
    </div>
</div>

{% endblock content %}

location_manager/templates/lcm/print.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        {% load static %}
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Locatia | {{subtitle}}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    </head>

    <body class="printable">
        <header>
			<div class="animate__animated animate__bounceIn title"  class="title"><h1>Informations Locataire</h1></div>
        </header>

        <article>
			<div class="container">
				<div class="col-md-8 mt-3">
					<ul class="list">
						<li class="list-item">
							<h2>Nom</h2>: {{ customer.lastname }}
						</li>

						<li class="list-item">
							<h2>Prénom</h2>: {{ customer.firstname }}
						</li>

						<li class="list-item">
							<h2>Maison</h2>: {{ customer.home }}
						</li>

						<li class="list-item">
							<h2>Chambre n°</h2>: {{ customer.roomid }}
						</li>

						<li class="list-item">
							<h2>Paiements</h2>:

							<table>
								<tr>
									<th scope="col">Date</th>
									<th scope="col">Payé</th>
								</tr>

								{% for p in customer.get_payments %}
								<tr>
									<td> {{p.date }}</td>
									<td> {% if p.paid %} Oui {%else%} Non {%endif%}</td>
								</tr>
								{% endfor %}
							</table>
						</li>
					</ul>
				</div>
			</div>		
		</article>
    </body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        {% load static %}
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Locatia | {{subtitle}}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    </head>

    <body>

        <header>
            {% block title %}
				<div class="animate__animated animate__bounceIn title"  class="title"><a href="{% url 'lcm:index' %}"><h1>Locatia</h1></a></div>
            {% endblock %}
        </header>

        <article>
            {% block content %}

            {% endblock content %}
        </article>

        {% block nav %}
        <nav class="navbar-expand-lg">
			<ul class="navbar-nav">
				<li>
					<a class="nav-link text-black font-weight-bold" href="{% url 'lcm:index' %}"> Accueil </a>
				</li>
                <li>
                    <a class="nav-link text-black font-weight-bold" href="{% url 'lcm:owners' %}">Clients</a> </li>
				<li>
					<a class="nav-link text-black font-weight-bold" href="{% url 'lcm:buildings' %}"> Maisons </a>
				</li>

                <li>
					<a class="nav-link text-black font-weight-bold" href="{% url 'admin:index' %}">Administration </a>
				</li>
			</ul>
        </nav>
        {%endblock%}
    </body>
</html>